//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuckooshka_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_
    {
        public string Cathegory { get; set; }
        public string ToDo { get; set; }
        public System.DateTime Time { get; set; }
        public string Comment { get; set; }
        public string Id { get; set; }
    }
}
